import { iconSVG } from './Icons.js';
const controls = [
  ['grid','Grade','Mostra ou oculta os contornos das respostas. Em modelos com referências, também inicia o acompanhamento.'],
  ['fit','Alinhamento automático','Ativa ou pausa o acompanhamento das quatro referências na câmera. Sem referências, este controle fica desativado.'],
  ['close','Fechar','Fecha a câmera ou a janela atual. Não salva uma correção.'],
  ['check','Aceitar e salvar','Após conferir foto, nota e aluno, registra a correção e sua evidência.'],
  ['retry','Repetir','Fotografa novamente ou permite escolher outro arquivo antes de aceitar.'],
  ['next','Próxima prova','Depois de salvar, prepara a próxima captura e avança o aluno da lista.'],
  ['finish','Finalizar','Depois de salvar, fecha a câmera e volta aos modelos. A evidência permanece no histórico.'],
  ['download','Baixar evidência','Na janela da evidência, baixa a imagem JPEG para guardar fora do navegador.']
];
export function helpGuideMarkup() {
  return `<p class="help-intro">Do modelo à nota em quatro passos. As imagens abaixo são capturas reais do aplicativo com dados de demonstração e câmera simulada.</p>
  <nav class="help-nav" aria-label="Seções da ajuda"><a href="#help-model">Modelo</a><a href="#help-camera">Câmera</a><a href="#help-review">Conferência</a><a href="#help-history">Histórico</a><a href="#help-icons">Ícones</a></nav>
  <section id="help-model"><h3>1. Prepare e aprove o modelo</h3><p>Na engrenagem ⚙, configure questões, alternativas, pontuação e identificação do aluno. Os ajustes válidos ficam salvos automaticamente neste navegador. Selecione um modelo existente ou use <strong>Criar folha com referências</strong>. Confira as versões preenchida e em branco e aprove o modelo.</p>
  <figure class="help-shot"><img src="./docs/images/modelo.png" alt="Prévia do modelo com opções para ver a folha em branco, compartilhar e aprovar" loading="lazy" width="1120" height="860"><figcaption>Distribua a versão em branco. A preenchida é o gabarito do professor.</figcaption></figure>
  <details><summary>Tenho uma imagem ou PDF próprio</summary><p>Importe o arquivo, escolha a página do PDF e recorte a área necessária. Aprove a imagem. Marque a primeira alternativa da primeira questão e a última alternativa da última questão; confira e ajuste cada ponto numerado. Informe as respostas corretas ou use a detecção da imagem preenchida.</p><p>Aprove o mapeamento e posicione as quatro referências em espaços brancos: superior esquerdo, superior direito, inferior direito e inferior esquerdo. Salve e confira. As versões exportadas recriam somente as respostas mapeadas e os blocos; não copiam enunciados. As cópias físicas dos alunos precisam conter essas referências.</p></details></section>
  <section id="help-camera"><h3>2. Enquadre e toque para fotografar</h3><p>Inclua toda a folha e os quatro blocos dentro da borda verde. Toque na imagem para capturar; não há botão de disparo. O ícone de grade revela os contornos e o alvo acompanha as referências. Se as marcas saírem da imagem, a grade desaparece. Modelos antigos sem referências exigem o mesmo enquadramento do cadastro.</p>
  <figure class="help-shot help-phone"><img src="./docs/images/camera.png" alt="Câmera ampliada com limite verde da fotografia, grade e controles de grade, alinhamento e fechar" loading="lazy" width="390" height="844"><figcaption>Use luz uniforme e mantenha a folha plana e nítida.</figcaption></figure></section>
  <section id="help-review"><h3>3. Confira o antes e depois e a nota</h3><p>Ao fotografar, o app enquadra a folha automaticamente pelas referências e calcula a nota. <strong>Antes</strong> mostra a foto original com os quatro cantos detectados; <strong>Depois</strong> mostra a imagem alinhada usada na leitura. A nota e os pontos aparecem acima. Os cantos são indicadores visuais, não alças para arrastar.</p>
  <figure class="help-shot"><img src="./docs/images/conferencia.png" alt="Conferência da prova com nota, rotação, diferença entre bordas e comparação entre foto original e corrigida" loading="lazy" width="1120" height="1150"><figcaption>Confira a fotografia e o aluno antes de aceitar. A nota ainda é uma prévia.</figcaption></figure>
  <p>A rotação, a diferença entre bordas e o desvio dos ângulos descrevem a transformação geométrica, não a certeza da correção. Se o enquadramento estiver errado, use a seta circular para repetir. Se as referências não forem reconhecidas, o app bloqueia o aceite e pede outra foto.</p><p>Confira o nome ou selecione o aluno e toque em ✓ para salvar a nota e a evidência. Só depois escolha a próxima prova ou finalize. Alterar a folha diante da câmera não muda a foto já capturada.</p></section>
  <section id="help-history"><h3>4. Consulte o histórico e guarde a evidência</h3><p><strong>Histórico</strong>, no cabeçalho, reúne as correções que você aceitou neste navegador: aluno, nota, pontos, data e imagem. Não é um registro de todos os cliques nem inclui prévias descartadas. Use <strong>Ver imagem</strong> e o ícone de download para baixar a evidência.</p>
  <figure class="help-shot"><img src="./docs/images/historico.png" alt="Histórico de correções aceitas com aluno, nota, pontos, data e botão para ver a evidência" loading="lazy" width="1120" height="700"><figcaption>A evidência preserva a nota, a foto corrigida e, quando há alinhamento, a foto original.</figcaption></figure>
  <p>Os dados ficam neste navegador e dispositivo, sem sincronização. Limpar os dados do site apaga os registros locais. Excluir um modelo não apaga as correções já aceitas.</p></section>
  <section id="help-icons"><h3>Guia dos ícones</h3><p>Os mesmos desenhos dos controles aparecem aqui. No computador, passe o cursor para ver o nome; leitores de tela também anunciam a função.</p>
  <dl class="icon-guide"><div><dt><span class="help-icon" aria-hidden="true">⚙</span>Configurações</dt><dd>Grade, formatos, referências, aparência do mapeamento, pontuação e alunos.</dd></div><div><dt><span class="help-icon" aria-hidden="true">?</span>Ajuda</dt><dd>Abre este manual com imagens e instruções.</dd></div>${controls.map(([icon,title,text])=>`<div><dt><span class="help-icon">${iconSVG(icon)}</span>${title}</dt><dd>${text}</dd></div>`).join('')}</dl></section>
  <details><summary>Se a leitura falhar</summary><p>Confira o modelo selecionado, melhore a iluminação, alise o papel e aproxime a câmera sem cortar os cantos. Os blocos precisam ter pelo menos 5 px na imagem gerada; 8 px é o padrão. Referências não identificam o conteúdo da prova: você deve escolher o modelo correto. Dobras, sombras, desfoque e papel curvo podem impedir o alinhamento. Mudanças nas posições das respostas ou referências exigem novas cópias impressas.</p></details>`;
}
